--! BETWEEN:
-- entre dos valores
-- incluye los valores extremos
SELECT FIRST_NAME, LAST_NAME, FOLLOWERS
FROM USERS
WHERE
    --FOLLOWERS > 4600 AND FOLLOWERS < 4700
    FOLLOWERS BETWEEN 4600 AND 4700
ORDER BY FOLLOWERS ASC;

--! MAX MIN COUNT ROUND AVG

-- COUNT: cuenta la cantidad de filas que devuelve una consulta
SELECT
    COUNT(*) AS TOTAL_USUARIOS,
    MIN(FOLLOWERS) AS MIN_FOLLOWERS,
    MAX(FOLLOWERS) AS MAX_FOLLOWERS,
    ROUND(AVG(FOLLOWERS)) AS AVG_FOLLOWERS
FROM USERS;

SELECT * FROM USERS;

--! GROUP BY
-- agrupa los resultados por un campo

SELECT FIRST_NAME, LAST_NAME, FOLLOWERS
FROM USERS
WHERE
    FOLLOWERS = 4
    OR FOLLOWERS = 4999;

SELECT COUNT(*), FOLLOWERS
FROM USERS
WHERE
    FOLLOWERS = 4
    OR FOLLOWERS = 4999
GROUP BY
    FOLLOWERS;

SELECT COUNT(*), FOLLOWERS
FROM USERS
WHERE
    FOLLOWERS BETWEEN 4500 AND 4999
GROUP BY
    FOLLOWERS
ORDER BY FOLLOWERS DESC;

--! HAVING
-- filtra los resultados de un GROUP BY

SELECT COUNT(*) AS TOTAL, COUNTRY
FROM USERS
GROUP BY
    COUNTRY
HAVING
    COUNT(*) BETWEEN 1 AND 5
ORDER BY COUNTRY ASC;

--! DISTINCT
-- elimina los resultados duplicados

SELECT DISTINCT COUNTRY FROM USERS;

--! GROUP BY CON OTRAS FUNCIONES AGREGADAS

SELECT * FROM USERS;

SELECT COUNT(*), SUBSTRING(
        EMAIL, POSITION('@' IN EMAIL) + 1
    ) AS DOMAIN
FROM USERS
GROUP BY
    DOMAIN
HAVING
    COUNT(*) > 1
ORDER BY COUNT(*) DESC;

--! SUBQUERIES
-- una consulta dentro de otra consulta

SELECT "DOMAIN", "TOTAL"
FROM (
        SELECT COUNT(*) AS "TOTAL", SUBSTRING(
                EMAIL, POSITION('@' IN EMAIL) + 1
            ) AS "DOMAIN"
        FROM USERS
        GROUP BY
            "DOMAIN"
        HAVING
            COUNT(*) > 1
        ORDER BY COUNT(*) DESC
    ) AS DOMAINS;